### ISSUE TITLE
Fieldsets for radios, checkboxes and date inputs are too restrictive

### ISSUE THREAD

**Issue by sussexrick** [gunndabad/govuk-frontend-aspnetcore#251]
If you use `<govuk-fieldset>` there is no restriction to the child components you can include.

If you use `<govuk-radios><govuk-radios-fieldset /></govuk-radios>` or the equivalent structures for checkboxes or date inputs, they are restricted.

When using this structure with `<govuk-radios-fieldset-legend is-page-heading="true" />` the question forms the entire body of the page. Our editors are looking to add more help and notes for that question between the heading and the radio buttons, but the only option they have is the `<govuk-radios-hint />` and this is proving too restrictive. They want to be able to use components like 'Inset text', Warning text' and 'Details' (I think these are the only likely candidates) as well as generic HTML like `<p class="govuk-body">`.

Is it possible to loosen the restrictions on these fieldsets to allow these other components?

**Comment by gunndabad** [comment]
This isn't possible due to how the component markup is generated; adding arbitrary markup next to 'virtual' tag helpers like `<govuk-radios-hint>` (that don't render anything themselves) doesn't work.

In this case using a top-level `<govuk-fieldset>` instead of one on the `radios` itself is probably the way to go.

**Comment by sussexrick** [comment]
Thanks, I'm happy to try rewriting our code to use the generic `<govuk-fieldset />`. Seems a shame not to use your built-in support radios etc as page heading given you've put all the effort into it though.

If we discount the arbitrary HTML part of the request, is the rest possible by specifying extra allowed child elements?

If so, maybe the arbitrary HTML scenario could work by creating a wrapper like `<govuk-text>` as a new allowed child type?

**Comment by gunndabad** [comment]
>If we discount the arbitrary HTML part of the request, is the rest possible by specifying extra allowed child elements?
If so, maybe the arbitrary HTML scenario could work by creating a wrapper like `<govuk-text>` as a new allowed child type?

It's not much easier with other `govuk-` tag helpers. The difficulty is keeping track of _where_ these elements should render. As a rule the output markup structure should match the order of the Razor (it would be very weird if you had, say, a `<govuk-text>` element between a `<govuk-radios-hint>` and a `<govuk-radios-item>` and the `<govuk-text>` wasn't rendered between the hint and the item). Making that work is complex.

>Seems a shame not to use your built-in support radios etc as page heading given you've put all the effort into it though.
Tag helpers are intended to mirror what's available in the corresponding nunjucks template. As a rough guide, if the nunjucks template doesn't support if then neither will the tag helper.

**Comment by sussexrick** [comment]
Closing as this can be achieved using `<govuk-fieldset />`. Thanks for the suggestion.
