### ISSUE TITLE
Two Colum Grid Layout missing area deifntions

### ISSUE THREAD

**Issue by AlexBeesley** [gunndabad/govuk-frontend-aspnetcore#277]
The areas of the TPR Block grid for two column layout have not been set and despite setting them manually on client projects of this package, since they come from the NuGet they are unset with each fresh install, this cause any content set within a two column layout to be lost.

![image](https://github.com/gunndabad/govuk-frontend-aspnetcore/assets/90189167/00ea80d8-4a46-492e-b588-2111d6ea1270)
![image](https://github.com/gunndabad/govuk-frontend-aspnetcore/assets/90189167/c591f584-53ff-429b-ab38-3bcedc0f26b4)

**Comment by gunndabad** [comment]
@sussexrick is this one for you?

**Comment by AlexBeesley** [comment]
@gunndabad Apologies, yes wrong repo.
