### ISSUE TITLE
http404 issues when not hosted on root

### ISSUE THREAD

**Issue by daxydoggie** [gunndabad/govuk-frontend-aspnetcore#285]
Hi,

Thanks for the previous fix for hosting as sub app/site.

We're now noticing 404 issues to resources not being found around the opengraph image and frontend js files when hosted **not** on the root.

for example:-

hosted on 

https://outreach-dev.north-norfolk.gov.uk/formsinternal

the markup is generated as

![{89C58B1A-79FA-422A-8598-2053DAD914DF}](https://github.com/user-attachments/assets/1ac74642-8391-47af-a75f-aaea78ab5e26)

As you can see there is a duplicate basepath here for the opengraph image and is getting reported as a 404 (not that we display the image).

also, when using f12 devtools to inspect the page we get a batch of three 404s reported:

404 /formsinternal/govuk/govuk-frontend.min.js.map
404 /formsinternal/govuk/govuk-frontend.min.js.map
404 /formsinternal/govuk/govuk-frontend.min.css.map

Can you investigate please. If you need any more info please let me know.

Thanks,
Craig.

**Comment by gunndabad** [comment]
Hi @daxydoggie 

I've pushed a fix for the Opengraph image so that will be available in the next release ( 3b694eb9f7d789f050d9f5b71dfdf9e73fc886b3).

Regarding the sourcemap files, do you definitely need those hosting? For those to work we'd also need to host all the pre-bundled source files.

**Comment by daxydoggie** [comment]
thanks for this. how do i turn off this feature?

**Comment by gunndabad** [comment]
> thanks for this. how do i turn off this feature (sourcemap files)? you mean just with f12 dev tools?

As far as I know it can't be turned off.

**Comment by gunndabad** [comment]
@daxydoggie 54d22e17534c4f22fb42a0c4e0dc10f53c8d4acd should fix the 404s for the sourcemaps

**Comment by daxydoggie** [comment]
Thanks for that. We've tried to upgrade our package (v2.2.0) but i see your are now targeting .NET8. with later versions.
We will no doubt target .NET8 in due course but at present we are on .NET6.
Is there any breaking changes or functionality that would prevent you targeting multiple frameworks ie .NET6/7/8?

Please let me know. Thanks, Craig.

**Comment by gunndabad** [comment]
> Thanks for that. We've tried to upgrade our package (v2.2.0) but i see your are now targeting .NET8. with later versions. We will no doubt target .NET8 in due course but at present we are on .NET6. Is there any breaking changes or functionality that would prevent you targeting multiple frameworks ie .NET6/7/8?
> 
> Please let me know. Thanks, Craig.

Yes, we’re now using features that require .NET 8. The intention is to support the .NET versions that are in support only.
